### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ciaociaociaociao** [febinrev/febrev-venom#2]
STARTING FEBREV VENOM......#######################
Traceback (most recent call last):
  File "febrev-venom.py", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'

**Comment by ciaociaociaociao** [comment]
just pip3 install click
fixed

**Comment by ciaociaociaociao** [comment]
pip3 install click


lol

**Comment by febinrev** [comment]
Yeah,,,,, the tool is now updated with bug fixes and attractive colours

**Comment by febinrev** [comment]
Yeah,,,,, the tool is now updated with bug fixes and attractive colours
